---
shared:
  image: node:12
jobs:
  publish_other-namespace_template:
    requires: [~pr, ~commit]
    environment:
      SD_TEMPLATE_PATH: ./templates/test-publish.yaml
    steps:
    - install_prerequisites: npm install -g screwdriver-template-main
    - publish:  template-publish
    - autotag: template-tag --name othernamespace2/template2 --tag latest
